
# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

# Text to speech
tts:
  - platform: google_translate

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
sensor:
  - platform: command_line
    name: shopping_list
    command: sed -n '/{/p' .shopping_list.json | awk '/./ { COUNT +=1 } END { print COUNT }'
    scan_interval: 10