esphome:
  name: bmp-ds-aht10

esp8266:
  board: esp01_1m

  # Example configuration entry
dallas:
  - pin: GPIO3

i2c:
  - id: bus_i2c
    sda: GPIO0
    scl: GPIO2

sensor:
  - platform: dallas
    address: 0x210119128497da28
    name: "Temperature"
  - platform: bme280
    i2c_id: bus_i2c
    pressure: 
      name: "Pression"
    humidity: 
      name: "Humidité"
    address: 0x77


# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "qjNv5yVypwj8pNzv8uJImc4g0BY7R0FdBdeCB8juxm0="

ota:
  password: "19ef448f0eaf716404f52802231b8b43"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Bmp-Ds-Aht10 Fallback Hotspot"
    password: "CBslppzSyg79"

captive_portal:
    