esphome:
  name: "d1mini-aht10-pitinfo"

esp8266:
  board: esp01_1m
i2c:
  - id: bus_i2c
    sda: GPIO4
    scl: GPIO5
    
uart:
  id: uart_bus
  rx_pin: GPIO3
  baud_rate: 1200
  parity: EVEN
  data_bits: 7
  debug:

teleinfo:
  update_interval: 60s
  historical_mode: true

sensor:
  - platform: aht10
    temperature:
      name: "Cave : Température"
    humidity:
      name: "Cave : Humidité"
  - platform: teleinfo
    tag_name: "PAPP"
    name: "papp"
    unit_of_measurement: "VA"
    icon: mdi:flash

# Enable logging
logger:
  level: VERBOSE
  baud_rate: 0
  esp8266_store_log_strings_in_flash: False
  
# Enable Home Assistant API
api:

ota:


wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Esphome-Web-0806C3"
    password: "QAdagHrdGV4H"

captive_portal:
    